---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Con **num** = 7 se imprime "d"
  checked: false
- value: Con **num** = 10 se imprime "d" y  se imprime "a"
  checked: false
- value: No es posible imprimir simultaneamente "a" y "d"
  checked: true
- value: Con **num** = 7 se imprime "a" y posteriormente se imprime "d"
  checked: false
name: Ejercicio 1
