---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: true
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Con **num** = 7 se imprime "d"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Con **num** = 10 se imprime "d" y  se imprime "a"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No es posible imprimir simultaneamente "a" y "d"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Con **num** = 7 se imprime "a" y posteriormente se imprime "d"
  checked: false
name: Condicionales Anidados e Indentación
