---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A and B and C
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: not A or B
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: len("Marta") == 4 or True
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A or not B and A==B
  checked: true
name: Operadores Lógicos
