---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "-10 < 0"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: for i in lista == 1
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 3**2 == 6
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 8 > 5
  checked: true
name: Expresión condicional
